# =============================
# Dependabot Configuration
# =============================
# This config enables weekly updates for NuGet, dotnet-sdk, npm, GitHub Actions, and Docker dependencies.
# Major version updates for dotnet-sdk and Docker images are ignored for stability.
# =============================

version: 2
updates:
  # NuGet packages (backend)
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
  # .NET SDK (backend)
  - package-ecosystem: "dotnet-sdk"
    directory: "/backend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
  # NPM packages (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Docker image dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "dotnet/*"
        update-types:
          - "version-update:semver-major"
