# =============================
# PR Cache Cleanup Workflow
# =============================
# This workflow deletes caches associated with closed pull requests.
# Helps keep GitHub Actions cache usage low.
# =============================

name: Cleanup PR Caches

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    name: Delete PR Caches
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache keys for PR..."
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
